stages:
  brew check:
    setup:
      - apply:
          pipeline: tools/brew
  jq check:
    description: check if jq exists and if not install it.
    when:
      condition:
        operator: exit_code_not_equals
        command: jq --version
        compareTo: 0
    setup:
      - command: brew install jq